### PR TITLE
Fix windows hidden test

### PR DESCRIPTION
**Pull request by Adirelle**
It appeared that:

1. The drive root always has the "SYSTEM" attribute set, which caused all the files to be considered as hidden.
2. On Windows, the file attributes are accessible through Fileinfo.Sys() and syscall constants & structs, so there is no need for golang.org/x/sys/windows.

### CODE REVIEW

**Comment by anacrolix** [comment]
I think it's recommended to avoid syscall when possible in favour of the golang.org/x/sys stuff.

**Comment by Adirelle** [comment]
I see. The issue is that the interface{} returned by FileInfo.Sys() is a *syscall.Win32FileAttributes and cannot be cast to its golang.org/x/sys equivalent.

**Comment by Adirelle** [comment]
I see. The issue is that the interface {} returned by FileInfo.Sys() is a *syscall.Win32FileAttributes and cannot be cast to its golang.org/x/sys equivalent.

**Comment by Adirelle** [comment]
Anyway, I will remove the second commit.

**Pull request merged**
