### PR TITLE
Add a sample systemd .service file to use DMS as a system service

### PR DESCRIPTION
**Pull request by scottchiefbaker**

### CODE REVIEW

**Review by anacrolix — APPROVED** [review]

**Comment by GwynethLlewelyn** [comment]
A simple note (which will avoid losing _an hour_ in figuring out what's wrong): since this `systemd` unit is meant to be run as a _user_, it should be the _user_ setting everything up, _not_ `root` — which was my mistake 🤣 I seldom use the ability of individual users to run their own units, although it's so convenient... I just keep forgetting that. 

One might also consider enabling lingering on the user running this service unit, since it's likely one wants to have `dms` running even when the user is not logged in:

```bash
# loginctl enable-linger USERNAME
```
I got the tip from [AskUbuntu](https://askubuntu.com/a/859583/84313), but it should work on any `systemd`-compatible OS. [Documentation for the lingering option of `loginctl` is also available online](https://www.freedesktop.org/software/systemd/man/loginctl.html#enable-linger%20USER%E2%80%A6) (in terse format!)

Under Ubuntu 22.04 LTS (my test case!) it _might_ be necessary to add to that particular user's `.profile` the following default variables:

```bash
export XDG_RUNTIME_DIR="/run/user/$UID"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
```
In my scenario, the issue was that this particular user didn't have its home directory set to the 'usual default' (i.e. `/home/USERNAME`) and that confused `systemctl` a bit. This might not be required under a 'standard' configuration of a 'normal' user, so to speak. YMMV!

**Comment by anacrolix** [comment]
I'm not an active Linux user atm, you are welcome to submit a PR if you wish, I will defer to your judgment. @scottchiefbaker do you have any insight?

**Comment by scottchiefbaker** [comment]
I think the file I provided is sufficient. The example above is a corner-case. It's documented in the file itself to use `--user`, so I think we're good.

**Comment by GwynethLlewelyn** [comment]
Obviously, I defer to your judgement, which will cover at least all cases where DMS is being used _only when the user is logged in_ — which _will_ be the case on Linux desktop/laptop systems, for instance. When nobody is logged in, it's very likely the computer is shut down :) so it would be pointless to run DMS :-)

I agree that this would be a more typical scenario.

What you describe as a 'corner-case' applies to Linux _server_ scenarios. The server is supposed to be running 100% of the time, 24h/day, no matter how many users are logged in to it at the moment. It is also a good practice to run services under their own account (as opposed to running them as `root`) in order to compartmentalise them, so it makes sense to run DMS from the user's `systemd` instead of from the 'main', system-wide `systemd`. That scenario is hardly a 'corner-case' when running services on a server... it's standard practice (that's the main reason why _I_ struggled with it!).

_Personally_ I actually prefer a mixed approach: have the `.service` file on a user's home directory with their permissions, but have the system-wide `systemd` pick it up. It's probably not the safest option (unless you implicitly trust that user blindingly!) but it _might_ make more sense under the following assumptions:

1. Services meant to run 24h/7 on a server are activated from the system-wide `systemd`.
2. Services meant to run _only when a specific user logs in_  are called from their user's own private (user-level) `systemd` instead, and are shut down when the user leaves.

I believe this is the 'intended' behaviour of having user-level `systemd` configuration (makes sense for desktop/laptop environments: there is a lot that simply does _not_ need to be running _if_ no user is present!), and that's the paradigm that DMS also assumes by default.

The whole point of my long comments is to explain that running DMS as a standalone, daemonise service that is available 24h/7 is _not_ a 'corner-case' at all, but _might_ be the more frequent approach for those using DMS on a (headless) server to, well, provide the kind of service DMS does — all the time.

**Comment by scottchiefbaker** [comment]
I understand what you're saying, but I think you're mistaken. I'm running `dms` as my `bakers` user using the systemd `.service` in this pull request and the service is up 100% of the time, and is **not** tied to whether I'm logged in to the box or not.

There probably is an argument that perhaps `dms` should be run as root instead of a local user. It's always "just worked" for me so I never worried about it.

**Comment by scottchiefbaker** [comment]
FWIW I had this working as a user service with CentOS 7 back in the day, and on my current Rocky 9.2 system as well.

**Comment by anacrolix** [comment]
Well I'm just glad people are finding it useful :). Thanks for discussing this.

**Pull request merged**
