### PR TITLE
add optional OnBrowseDirectChildren and OnBrowseMetadata interfaces

### PR DESCRIPTION
**Pull request by tsynik**
This PR add ability to use external functions to serve dlna content. No changes to current logic if not defined.

### CODE REVIEW

**Comment by anacrolix** [comment]
Any way to do this by just having the new fields set to the defaults by default?

**Comment by tsynik** [comment]
> Any way to do this by just having the new fields set to the defaults by default?

We use those in TorrServer to serve torrents from DB via DLNA - there is no actual filesystem so it's layer to generate needed objects.

**Comment by anacrolix** [comment]
Ah yeah no worries, I mean can the default implementations (the ones used if the fields are nil) be set as the default further up during initialization or is that too difficult (like the existing API use doesn't require using a default initializer/constructor already where we can put it)?

**Comment by tsynik** [comment]
> Ah yeah no worries, I mean can the default implementations (the ones used if the fields are nil) be set as the default further up during initialization or is that too difficult (like the existing API use doesn't require using a default initializer/constructor already where we can put it)?

You mean full rewrite of Handle(action string, argsXML []byte, r *http.Request) function without those interfaces? Matt, I'm not a go guru as you ;-) The idea of this PR was use upstream not fork in downstream project.

**Comment by anacrolix** [comment]
All good, thanks for the contribution.

**Pull request merged**
