### PR TITLE
Make device icon configurable

### PR DESCRIPTION
**Pull request by triole**
Great work. But I needed the device icon to be configurable. Maybe you want to pull this.

### CODE REVIEW

**Comment by anacrolix** [comment]
Maybe it's out of the scope of this PR, but would you want to just keep the larger Sonic icon, and resize for the other one? Then we can also set the default for the flag to the single Sonic icon file path, and reduce the special cases?

**Comment by triole** [comment]
I removed the small icon and applied the rescale to the larger one. That was what I wanted to do anyway but I did not find the time yesterday. Now it should be fine. 

Please have a look and feel free to change whatever you want to do differently.

**Comment by anacrolix** [comment]
Let me know if the change works for you for both the default, and your custom icon, and if so I'll merge. Cheers

**Comment by triole** [comment]
Works like a charm. Depending on the client I use sometimes there are chaching issues. The icon does not change immediately. But this doesn't have to do with dms I suppose. Thank you.

**Pull request merged**
