### PR TITLE
FreeBSD service documentation and file

### PR DESCRIPTION
**Pull request by halfwit**
If anyone else uses FreeBSD, this service file may be of use.

### CODE REVIEW

**Comment by anacrolix** [comment]
If this is definitely bsd-specific, could they be in a bsd directory? Also should there be a directory just for auxiliary/helper stuff for various OS, rather than a bunch of mysterious (for people that don't use whatever OS flavor the files are for) things floating around in the source code? Open to suggestions!

**Comment by halfwit** [comment]
I have no strong  opinions, the notion of a helper directory is the best in my opinion

**Comment by anacrolix** [comment]
Any preference for naming that? Maybe just `helpers` and put this under `bsd`? Any other helpers for stuff like this can be moved in there too.

**Comment by halfwit** [comment]
I like it

**Comment by halfwit** [comment]
I also cleaned up the link for systemd in the readme :)

**Comment by anacrolix** [comment]
Thanks very much!

**Pull request merged**
